### PR TITLE
cgosqlite: import SQLite amalgamation v3.46.1

### PR DESCRIPTION
**Pull request by raggi**
- Add script to partially automate SQLite updates
- Run with https://sqlite.org/2024/sqlite-amalgamation-3460100.zip
- Removed compiler warning suppression that is no longer required.

Updates https://github.com/tailscale/corp/issues/22321

### CODE REVIEW

**Review by creachadair — APPROVED** [review]

**Comment by bradfitz** [comment]
Can you add some docs in this PR too about how one updates this manually?

**Comment by raggi** [comment]
> Can you add some docs in this PR too about how one updates this manually?

I added a shell script that codifies the process, and a quick pointer to it to the top level readme.

**Comment by willnorris** [comment]
why wouldn't the warning suppression still be required?  There doesn't appear to have been any movement on https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115274 and I'm still seeing the warning.  Was it addressed somewhere else?

**Comment by raggi** [comment]
Oh my apologies @will, I guess I built with clang and forgot it was a gcc warning, my bad

**Pull request merged**
